version: "3"
services:
  evanapmdb:
    restart: always
    image: mysql:8.0
    container_name: evanapmdb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"

  evanapmredis:
    restart: always
    image: redis:latest
    container_name: evanapmredis
    ports:
      - "6380:6379"
