input {
    beats {
        port => 5044
    }
}

filter {
    json{
        source => "message"
        target => "parsed_json"
    }
    mutate {
        add_field => { "time" => "%{[parsed_json][time]}" }
        add_field => { "level" => "%{[parsed_json][level]}" }
        add_field => { "app" => "%{[parsed_json][app]}" }
        add_field => { "hostname" => "%{[parsed_json][hostname]}" }
    }
    mutate {
        remove_field => [ "parsed_json" ]
    }
}
output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dogapm-%{[app]}-%{+YYYY.MM.dd}"
  }
}
