receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - 'attributes["drop"] == true'
  tail_sampling:
    decision_wait: 5s
    num_traces: 50000
    expected_new_traces_per_sec: 1
    policies:
      [
        {
          name: error-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: error, value: true },
        },
        {
          name: slowsql-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: slowsql, value: true },
        },
        {
          name: longTx-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: longTx, value: true },
        },
        {
          name: http-slow,
          type: numeric_attribute,
          numeric_attribute:
            { key: http.duration, min_value: 1, max_value: 1000000000 },
        },
        {
          name: http-status-error,
          type: string_attribute,
          string_attribute: { key: http.status_code, values: ["400", "500"] },
        },
        {
          name: grpc-slow,
          type: numeric_attribute,
          numeric_attribute:
            { key: grpc.duration, min_value: 1, max_value: 1000000000 },
        },
      ]

exporters:
  debug:
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
  zpages:
    endpoint: ":55679"
service:
  telemetry:
    metrics:
      level: detailed
      address: ":8888"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, tail_sampling]
      exporters: [debug, otlp/jaeger]
