receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - 'attributes["drop"] == true'
  tail_sampling:
    decision_wait: 5s
    num_traces: 50000
    expected_new_traces_per_sec: 1
    policies:
      [
        {
          name: error-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: error, value: true },
        },
        {
          name: slowsql-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: slowsql, value: true },
        },
        {
          name: longTx-always-sample,
          type: boolean_attribute,
          boolean_attribute: { key: longTx, value: true },
        },
      ]

exporters:
  debug:
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, tail_sampling]
      exporters: [debug, otlp/jaeger]
