global:
  scrape_interval: 15s #默认抓取周期
scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ordersvc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ordersvc:8080"]

  - job_name: "skusvc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["skusvc:8091"]

  - job_name: "usrsvc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["usrsvc:8092"]
